global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["webservice:8082"]
        labels:
            service: 'webservice'
            group: 'monitoring'
            name: 'webservice'